### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by sean-e-dietrich** [expressjs/vhost#11]
When testing locally and using Express 4 there appears to be an infinite loop to where it never goes onto the next request.

To fix this I had to remove the:
```
handle(req, res, next)
```
and replace with
```
return next();
```

This seemed to work for me. Is this because Connect is no longer apart of Express?

**Comment by dougwilson** [comment]
It shouldn't be, as this library doesn't require connect or even Express and should work with everything (the tests don't use either one). Can you post a fuller example I can run that reproduces the issue, please?

**Comment by sean-e-dietrich** [comment]
below is a sample of what I am attempting to do.
example.localhost and test.localhost are set to 127.0.0.1

the message I am now getting is:
```
RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
TypeError: Cannot read property 'hostname' of undefined
    at app.listen.host (/Users/sean/Desktop/node_projects/test/index.js:17:24)
    at Layer.handle [as handle_request] (/Users/sean/Desktop/node_projects/test/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/sean/Desktop/node_projects/test/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/sean/Desktop/node_projects/test/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/sean/Desktop/node_projects/test/node_modules/express/lib/router/layer.js:82:5)
    at /Users/sean/Desktop/node_projects/test/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/Users/sean/Desktop/node_projects/test/node_modules/express/lib/router/index.js:321:12)
    at next (/Users/sean/Desktop/node_projects/test/node_modules/express/lib/router/index.js:261:10)
    at vhost (/Users/sean/Desktop/node_projects/test/node_modules/vhost/index.js:37:14)
    at Layer.handle [as handle_request] (/Users/sean/Desktop/node_projects/test/node_modules/express/lib/router/layer.js:82:5)
```
this is the code I am using:
```javascript
var express = require('express'),
    vhost = require('vhost'),
    bodyParser = require('body-parser'),
    app = express(),
    domains = ['example.localhost','test.localhost'];

app.use(bodyParser.json());

domains.forEach(function(domain){
  app.use(vhost(domain,app));
});


app.get('/',function(req,res,next){
  var data = {
    'message': 'Output to browser',
    'domain': req.vhost.hostname
  }
  res.send(data);
});

var server = app.listen(5000, function () {
  var host = server.address().address;
  var port = server.address().port;

  console.log('App listening at http://%s:%s', host, port);
});
```

**Comment by dougwilson** [comment]
Ah. It's because your line `app.use(vhost(domain,app));` creates an infinite loop:

1. Request comes into `app`
2. Parse body
3. If request is from `example.localhost` or  `test.localhost`, direct to `app`; go to 1

**Comment by dougwilson** [comment]
You want to have 2 Express apps:
```js
var express = require('express'),
    vhost = require('vhost'),
    bodyParser = require('body-parser'),
    app = express(),
    app2 = express(),
    domains = ['example.localhost','test.localhost'];

app.use(bodyParser.json());

domains.forEach(function(domain){
  app.use(vhost(domain,app2));
});


app2.get('/',function(req,res,next){
  var data = {
    'message': 'Output to browser',
    'domain': req.vhost.hostname
  }
  res.send(data);
});

var server = app.listen(5000, function () {
  var host = server.address().address;
  var port = server.address().port;

  console.log('App listening at http://%s:%s', host, port);
});
```

**Comment by sean-e-dietrich** [comment]
Ok. Slightly confusing as to why I would need 2 Express Apps. But thank you for the clarification.

**Comment by dougwilson** [comment]
The entire purpose of this module is to have have multiple Express apps, where which Express app to use is based off the Host.

**Comment by sean-e-dietrich** [comment]
OH! Ok, thank you. I guess because I was using 1 app I didn't see the purpose but now I do. Once again thank you for the clarification.
